### ISSUE TITLE
Wrong Location

### ISSUE THREAD

**Issue by snydox** [flathub/org.gabmus.whatip#1]
I'm using a Panamanian VPN and for some reason it says that I'm in Cordoba, Argentina. However on ip-tracker.org it clearly states that the IP Address 138.186.142.203 belongs to Panama.
![whatip](https://user-images.githubusercontent.com/13590875/117891229-8c0cac00-b284-11eb-8f42-4fe521273b32.png)

**Comment by GabMus** [comment]
Wrong place to report a bug, you should report it here: https://gitlab.gnome.org/GabMus/whatip
